# Zeus Configuration File
# End-to-End ML Pipeline Configuration

# Data Configuration
data:
  # Training dataset configuration
  training:
    # Raw datasets to combine (list of directories)
    raw_datasets:
      - "../data/wet-0-soil-compaction-dataset"
      - "../data/wet-1-soil-compaction-dataset" 
      - "../data/wet-2-soil-compaction-dataset"
    # Target combined training dataset directory
    target_dataset: "../data/training-dataset"
    # raw_datasets:
    #   - "../data/wet-0-soil-compaction-dataset"
    #   - "../data/wet-1-soil-compaction-dataset" 
    #   - "../data/wet-2-soil-compaction-dataset"
    #   - "../data/field-soil-compaction-dataset"
    # # Target combined training dataset directory
    # target_dataset: "../data/combined-training-dataset"
  
  # Validation dataset configuration
  validation:
    # Raw validation datasets to combine
    raw_datasets:
      - "../data/field-soil-compaction-dataset"
    # Target combined validation dataset directory
    target_dataset: "../data/validation-dataset"
  
  # Dataset processing flags
  new_dataset: true  # Set to true to recreate datasets from raw data

# Feature Engineering Configuration
features:
  handcrafted:
    enabled: true  # Set to false to skip handcrafted feature generation
    # Number of top features to select
    n_features: 16
    
    # Which feature set to use for final model training
    # Options: "mutual_info", "correlation", "lasso", "random_forest", "all"
    chosen_method: "random_forest"

  pca:
    enabled: false
    n_features: 16
    visualize: true

  autoencoder:
    enabled: false
    n_features: 16
    load_model: false
    visualize: true
    save_models: true
    save_directory: "./models"
    epochs: 30
    patience: 10
    batch_size: 32
    verbose: 0
  
  pretrained_cnn:
    enabled: false
    n_features: 16
    load_model: false
    visualize: true
    save_models: true
    save_directory: "./models"
    img_size: [160, 160]
    batch_size: 32
    output_dir: "./cnn_temp_images"
    

# Model Configuration
models:
  ridge_regression:
    enabled: true
    degrees: [1, 2, 3]  # Polynomial degrees to test
    alpha: 1000         # Ridge regularization parameter
    
  random_forest:
    enabled: true
    n_estimators: 100

  gradient_boosted_tree:
    enabled: true
    n_estimators: 100

  svr:
    enabled: true

  mlp:
    enabled: false
    epochs: 30

  cnn_regressor:
    enabled: true
    epochs: 20
    img_size: [160, 160]
    batch_size: 32
    output_dir: "./cnn_temp_images_regressor"
    save_model: true
    save_directory: "./models"

  #   
  # svm:
  #   enabled: false
  #   kernel: "rbf"
  #   C: 1.0

# Advanced Configuration
advanced:
  verbose: true  # Set to false to reduce logging output