# Data configuration
data:       

  label_name: "Bulk Density (g/cm^3)"     # Name of label used data_log.csv
  new_dataset: false                       # Set to true if this is a new dataset

  # Training dataset 
  training:       
  
    # Raw datasets to combine (list of directories)
    dataset_dirs:       
      - "../data/wet-0-soil-compaction-dataset"
      - "../data/wet-1-soil-compaction-dataset" 
      - "../data/wet-2-soil-compaction-dataset"
      - "../data/field-soil-compaction-dataset"

    # Target combined training dataset directory
    target_dir: "../data/training-dataset"
  
  # Validation dataset
  validation:

    # Raw validation datasets to combine
    dataset_dirs:
      - "../data/field-2-soil-compaction-dataset"

    # Target combined validation dataset directory
    target_dir: "../data/validation-dataset"


advanced:
  verbose: true  # Set to false to reduce logging output